name: project1_2
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/canteen1.png
    - assets/images/canteen2.png
    - assets/images/canteen3.png
    - assets/images/nasi_goreng.png
    - assets/images/cold_coffee.png
    - assets/images/sate.png
